apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: database-pvc
  namespace: database
  labels:
    app: mysql
spec:
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteOnce