apiVersion: v1
kind: PersistentVolume
metadata:
  name: database-pv
  namespace: database
  labels:
    app: mysql
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/test
    server: 172.31.12.214

---
apiVersion: v1
kind: PersistentVolume
metadata:
  name: wordpress-pv
  namespace: database
  labels:
    app: wordpress
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /data/wordpress
    server: 172.31.12.214