apiVersion: v1
kind: Secret
metadata:
  name: secret
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  password: YWRtaW5AMTIzCg== #admin@123 # required field for kubernetes.io/basic-auth