apiVersion: v1
kind: Secret
metadata:
  name: secret-wordpress
  namespace: database
type: kubernetes.io/basic-auth
stringData:
  username: root # required field for kubernetes.io/basic-auth
  password: cmVkaGF0Cg== # required field for kubernetes.io/basic-auth