apiVersion: v1
kind: PersistentVolume
metadata:
  name: storage-pv
  labels:
    app: storageapp
spec:
  capacity:
    storage: 2G
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Recycle
  mountOptions:
    - hard
    - nfsvers=4.1
  nfs:
    path: /container_data/app1
    server: 172.31.3.79