apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: storage-pvc
  labels:
    app: storageapp
  namespace: storage
spec:
  resources:
    requests:
      storage: 2G
  accessModes:
    - ReadWriteOnce
