apiVersion: v1
kind: Secret
metadata:
  name: db-secret
  namespace: secure
  labels: 
    app: database
type: Opaque
data:
  password: cmVkaGF0Cg==   #echo redhat | base64
  username: ZGJ1c2VyCg==   #echo dbuser | base64
