# create a docker secret using kubectl command 
# kubectl create secret docker-registry NAME --docker-username=user --docker-password=password --docker-server=https://hub.docker.com 

# for yaml process we need docker json file 
# first login in registry using machine using docker login command 
# after login in yoour user home directory it will show .docker in this it will create json file.
# dockerconfigjson is a base64 encoded string:  cat ~/.docker/config.json | base64 -w 0 
# using above command it will generate secret pass in data secret in yaml 

apiVersion: v1
kind: Secret
metadata:
  name: docker-secret 
  namespace: secure 
  labels:
    app: database
data:
  .dockerconfigjson: ewoJImF1dGhzIjogewoJCSJodHRwczovL2luZGV4LmRvY2tlci5pby92MS8iOiB7CgkJCSJhdXRoIjogImNISmhkR1ZsYTJ0MWJXRjNZWFE2YVVCdGNHOXpjMmxpYkdWQU1UUT0iCgkJfQoJfQp9
type: kubernetes.io/dockerconfigjson