# create a Namespace
apiVersion: v1
kind: Namespace
metadata:
  name: mithen 

--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webmithen 
  namespace: mithen 
spec:
  selector:
    matchLabels:
      app: webmithen  
  template:
    metadata:
      labels:
        app: webmithen  
    spec:
      containers:
      - name: webmithen  
        image: prateekkumawat/mithen:web
        imagePullPolicy: Always
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80

---
kind: Service
apiVersion: v1
metadata:
  name: webmithen-svc
  namespace: mithen
spec:
  selector:
    app: webmithen
  type: NodePort
  ports:
  - name: webmithen-port
    port:  80
    targetPort: 80
    nodePort: 30993