apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql-service
  namespace: mithen 
spec:
  selector:
    matchLabels:
      app: mysql-service
  template:
    metadata:
      labels:
        app: mysql-service
    spec:
      containers:
      - name: mysql-service
        image: mysql:latest
        env: 
          - name: MYSQL_ROOT_PASSWORD
            value: redhat
          - name: MYSQL_USER
            value: prateek
          - name: MYSQL_PASSWORD
            value: redhat
        resources:
          limits:
            memory: "700Mi"
            cpu: "2"
        ports:
        - containerPort: 3306
---
kind: Service
apiVersion: v1
metadata:
  name: mysql-service-svc
  namespace: mithen
spec:
  selector:
    app: mysql-service
  type: NodePort
  ports:
  - name: mysql-service-port
    port: 3306
    targetPort: 3306
    nodePort: 30994